---
debian_baseline_timezone: Europe/Paris
debian_baseline_hostname: '{{ inventory_hostname }}'
debian_baseline_node_role: generic
debian_baseline_manage_repositories: true
debian_baseline_components: [main, contrib, non-free, non-free-firmware]
debian_baseline_password_authentication: false
debian_baseline_permit_root_login: prohibit-password
debian_baseline_guest_agent: true
debian_baseline_manage_services: true
debian_baseline_unattended_reboot: false
debian_baseline_sections: [apt, identity, shell, ssh, services, unattended]
