---
- name: Enable common VM services
  ansible.builtin.service:
    name: '{{ item }}'
    enabled: true
    state: started
  loop: [ssh, chrony, rsyslog]
  when: debian_baseline_manage_services | bool

- name: Start the QEMU Guest Agent on virtual machines
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
  when: debian_baseline_manage_services | bool and debian_baseline_guest_agent | bool
